### PR TITLE
Adds 10 movie quotes to movies.json [closes #2]

### LINKED ISSUE #2: Add Movie Quotes
Add movie quotes to `data/movies.json`

### PR DESCRIPTION
**Pull request by sernadesigns**
I have added 10 movie quotes and data.

I wasn't sure how you wanted to handle the semver versioning.
Please let me know if you want this change to be under a patch or minor version change.

### CODE REVIEW

**Comment by sernadesigns** [comment]
Not sure why the tests keep failing. Looks like there is an issue for this though. [#26](https://github.com/Snipey/popular-quotes/issues/26)

**Comment by Snipey** [comment]
The initial tests I posted worked for the dummy data I had but are now broken because i think I configured the CI wrong

**Comment by sernadesigns** [comment]
Makes sense. Thanks for the quick feedback!

**Comment by sernadesigns** [comment]
@Snipey I see here that my branch was merged, but I don't see my entries in the `master` branch. Was there a problem?

**Comment by Snipey** [comment]
Whoops my bad. I had to merge 40 of these. I think I got rid of it because I'm not sure if this is a quote. Its 2 words and not from a classic movie as it says 2020 is the year.
```json
[
  {
	"quote": "Black widow",
	"character": "Natasha Sebastian",
	"title": "Fire woman",
	"actor": "Amy Jackson",
	"year": 2020
  }
]
```

**Comment by sernadesigns** [comment]
Hmm. That quote was not added by me. I think that one snuck in before I made my commit. It appeared when I got latest before my push.

I added 10 movies quotes, all from 80s movie classics.

Are you able to retrieve them, or should I resubmit a PR?

**Comment by Snipey** [comment]
Resubmit the pr and I will merge :)

**Pull request merged**
